[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.14.0",
    "python-dotenv>=1.0.1",
    "telethon>=1.37.0",
]
